<script lang="ts">
	import type { PageProps } from './$types';
	let { data }: PageProps = $props();
</script>

<svelte:head><title>About &amp; credits · Aṣṭādhyāyī Explorer</title></svelte:head>

<div class="wrap page prose">
	<p class="eyebrow">About</p>
	<h1>About &amp; credits</h1>
	<p>
		Aṣṭādhyāyī Explorer is a free, open learning tool for people who read Devanagari and want to understand Pāṇini's
		grammar in depth, using English as the language of explanation.
	</p>

	<h2>Data</h2>
	<ul>
		<li>
			<b>Sūtra text, padaccheda, anuvṛtti, adhikāra, sūtra types, commentaries and examples</b> come from
			<a href="https://ashtadhyayi.com" rel="noopener">ashtadhyayi.com</a>'s
			<a href="https://github.com/ashtadhyayi-com/data" rel="noopener">open data repository</a>, used with thanks under its
			terms ("free to use … provided that appropriate credits are mentioned"). Snapshot:
			<code>{data.meta.sha.slice(0, 10)}</code>, {data.meta.count} sūtras.
		</li>
		<li>
			<b>English translation:</b> Śrīśa Chandra Vasu, <i>The Ashtadhyayi of Panini</i> (1897), and the ashtadhyayi.com
			sūtrārtha translations.
		</li>
		<li><b>Sanskrit commentaries:</b> Kāśikāvṛtti (Vāmana &amp; Jayāditya), Siddhānta Kaumudī (Bhaṭṭoji Dīkṣita), and vārttikas of Kātyāyana.</li>
		<li>
			<b>Word derivations</b> (derivation debugger, coming soon) are generated by
			<a href="https://github.com/ambuda-org/vidyut" rel="noopener">vidyut-prakriya</a> from the Ambuda project (MIT licence).
		</li>
	</ul>

	<h2>How to read the colours</h2>
	<p>
		On every sūtra page, words are coloured by the role their case ending usually plays, following the meta-rules
		1.1.49 (6th case = "in place of"), 1.1.66 (7th case = "before") and 1.1.67 (5th case = "after"). This is a reading aid
		derived automatically from the padaccheda; the tradition's own interpretation, given in the commentaries, always takes
		precedence.
	</p>

	<h2>Corrections</h2>
	<p>
		Errors in the underlying text or commentaries are best reported on ashtadhyayi.com (each sūtra page links there), so
		every project that uses the data benefits.
	</p>
</div>

<style>
	.page { padding-top: 36px; max-width: 760px; }
	h1 { font-size: clamp(32px, 5vw, 44px); }
	h2 { margin-top: 1.6em; font-size: 24px; }
	.prose { font-size: 16.5px; }
	li { margin-bottom: 0.6em; }
	code { font-family: var(--font-mono); font-size: 0.9em; background: var(--surface-2); padding: 1px 5px; border-radius: 4px; }
</style>
